### ISSUE TITLE
a couple of bugs

### ISSUE THREAD

**Issue by mathewzilla** [thomasdeneux/spikes#5]
Hi,
Thanks for making this code available. The algorithm looks really useful. 

I'm trying out your algorithms (on the MLspike repo, but there is no way to post issues there) and found a couple of bugs:

1. help/spk_factorbox.html does not have any of the code output content - it seems a licence error prevented the code from executing for the version on github.

2. running spk_factorbox.m locally does not work as a function - simul_noiseequalizer - is missing

3. spk_autocalibration is giving an error when run as part of spk_demo as non-doubles are being sent to fmincon. This can be fixed by wrapping the function 'energy' with double(), but there may be a more elegant solution...

I hope these bug reports are useful!

**Comment by MLspike** [comment]
Thanks for this bug report. I have now solved the 3 issues.
Best regards, Thomas

**Comment by MLspike** [comment]
Dear Mathew,

Thank you for this bug report, helpful indeed! I have now solved the 
three issues that you rised in the last github commit.

Some details below.

Good luck with MLspike and don't hesitate to ask your questions.

Regards,
Thomas Deneux


Le 27/03/2017 à 16:05, Mathew Evans a écrit :
>
> Hi,
> Thanks for making this code available. The algorithm looks really useful.
>
> I'm trying out your algorithms (on the MLspike repo, but there is no 
> way to post issues there) and found a couple of bugs:
>
> 1.
>
>     help/spk_factorbox.html does not have any of the code output
>     content - it seems a licence error prevented the code from
>     executing for the version on github.
>
indeed, i had pressed 'Publish' but not even checked that the result was 
correct!

>
> 1.
>
>     running spk_factorbox.m locally does not work as a function -
>     simul_noiseequalizer - is missing
>
indeed, i have added it
>
> 1.
>
>     spk_autocalibration is giving an error when run as part of
>     spk_demo as non-doubles are being sent to fmincon. This can be
>     fixed by wrapping the function 'energy' with double(), but there
>     may be a more elegant solution...
>
this bug was introduced by a recent change in the main tps_mlspike 
function, which stores some variables as single or uint8 to save memory; 
i have now solved it
